services:
  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/workspace:cached
      - .:/mythographer
    command: sleep infinity
    network_mode: service:postgres
volumes:
  redis:
  postgres:
